aww:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  # First Leg
  LF_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HAA
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  LF_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  LF_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_KFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  # Second Leg
  RF_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HAA
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  RF_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  RF_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_KFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  # Third Leg
  LH_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HAA
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  LH_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  LH_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_KFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  # Fouth leg
  RH_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HAA
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  RH_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}
  RH_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_KFE
    pid: {p: 1000.0, i: 0.1, d: 10.0}
